### ISSUE TITLE
Theorem contrapositive in Logic.v

### ISSUE THREAD

**Issue by prishitakadam** [marshall-lee/software_foundations#1]
I believe the theorem contrapositive is incorrect in Logic.v!

This seems to work:
`Theorem contrapositive : forall (P Q : Prop),
  (P -> Q) -> (~Q -> ~P).`
Proof.
 ` intros P Q NPQ NQ NP.`
 `unfold not in NQ. apply NQ in NPQ. apply NPQ. apply NP.`
Qed.

**Comment by marshall-lee** [comment]
why do you think it's incorrect? it works too

**Comment by marshall-lee** [comment]
@prishitakadam note that i pushed the new version of files to repo, it's 6.1 now
